config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :examples
  
  root 'home#index'
end

app/models/example.rb
class Example < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, 
         :registerable,
         :recoverable, 
         :rememberable, 
         :trackable, 
         :validatable,
         :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  include Pagination
  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/pagination.rb
module Pagination
  def page
    params[:page] || 1
  end

  def per_page
    params[:per_page] || 20
  end
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_example, only: [:show, :edit, :update, :destroy]

  # GET /examples
  # GET /examples.json
  def index
    @examples = Example.page(page)
                       .per(per_page)
  end

  # GET /examples/1
  # GET /examples/1.json
  def show
  end

  # GET /examples/new
  def new
    @example = Example.new
  end

  # GET /examples/1/edit
  def edit
  end

  # POST /examples
  # POST /examples.json
  def create
    @example = Example.new(example_params)

    respond_to do |format|
      if @example.save
        format.html { redirect_to @example, notice: 'Example was successfully created.' }
        format.json { render :show, status: :created, location: @example }
      else
        format.html { render :new }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /examples/1
  # PATCH/PUT /examples/1.json
  def update
    respond_to do |format|
      if @example.update(example_params)
        format.html { redirect_to @example, notice: 'Example was successfully updated.' }
        format.json { render :show, status: :ok, location: @example }
      else
        format.html { render :edit }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /examples/1
  # DELETE /examples/1.json
  def destroy
    @example.destroy
    respond_to do |format|
      format.html { redirect_to examples_url, notice: 'Example was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_example
      @example = Example.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def example_params
      params.require(:example).permit(:name, :favorite_color)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_type_from_flash(msg_type)
    case msg_type
      when "error"   then "alert-danger"
      when "alert"   then "alert-warning"
      when "success" then "alert-success"
      else                "alert-info"
    end
  end
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/views/examples/_form.html.slim
= form_for @example do |f|
  - if @example.errors.any?
    #error_explanation
      h2 = "#{pluralize(@example.errors.count, "error")} prohibited this example from being saved:"
      ul
        - @example.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :favorite_color
    = f.text_field :favorite_color
  .actions = f.submit

app/views/examples/edit.html.slim
h1 Editing example

== render 'form'

= link_to 'Show', @example
'|
= link_to 'Back', examples_path

app/views/examples/index.html.slim
h1 Listing examples

table
  thead
    tr
      th Name
      th Favorite color
      th
      th
      th

  tbody
    - @examples.each do |example|
      tr
        td = example.name
        td = example.favorite_color
        td = link_to 'Show', example
        td = link_to 'Edit', edit_example_path(example)
        td = link_to 'Destroy', example, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Example', new_example_path

app/views/examples/new.html.slim
h1 New example

== render 'form'

= link_to 'Back', examples_path

app/views/examples/show.html.slim
p#notice = notice

p
  strong Name:
  = @example.name
p
  strong Favorite color:
  = @example.favorite_color

= link_to 'Edit', edit_example_path(@example)
'|
= link_to 'Back', examples_path

app/views/home/index.slim
h1 Great website. Ship it!

app/views/layouts/application.slim
doctype html
html
  head
    title
      | Beginnings
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    = render 'shared/header'
    = render 'shared/flash'
    .container
      == yield

app/views/shared/_flash.slim
.container
  - flash.each do |msg_type, message|
    .alert.alert-dismissible.fade.in role="alert" class="#{alert_type_from_flash(msg_type)}"
      button.close aria-label="Close" data-dismiss="alert" type="button" 
        span aria-hidden="true" ×
      = message

app/views/shared/_header.slim
header
  nav.navbar.navbar-dark.bg-primary.navbar-fixed-top
    h1.navbar-brand
      | Welcome
    ul.nav.navbar-nav
      li.nav-item.active
        = link_to "Home", root_url, class: "nav-link"
    ul.nav.navbar-nav.pull-xs-right
      - if user_signed_in?
        li.nav-item
          .btn-group
            button.btn.btn-light.btn-info-outline.dropdown-toggle.nav-username[
              aria-expanded="false" 
              aria-haspopup="true" 
              data-toggle="dropdown" 
              type="button"]
                = current_user.email
            .dropdown-menu
              = link_to "Sign out", destroy_user_session_path, method: "delete", class: "dropdown-item"
      - else
        li.nav-item
          = link_to "Log in", new_user_session_url, class: "nav-link"
        li.nav-item
          = link_to "Sign up", new_user_registration_url, class: "nav-link"